import { AlertTriangle, CalendarCheck2, CheckCircle2, Clock3, Download, GraduationCap, Layers3, ListChecks, Percent, UserRoundCheck, UsersRound } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { StatusPill } from "@/components/status-pill";
import { requireRoles } from "@/lib/auth";
import { getMonitoringData, normalizeMonitoringPeriod } from "@/lib/monitoring";
import { formatDateId, formatDateTimeId } from "@/lib/utils";
import { db } from "@/db";
import { schoolClasses } from "@/db/schema";
import { eq } from "drizzle-orm";
import { attendanceFilterParams, parseAttendanceFilter } from "@/lib/attendance-filters";

const statusMeta = {
  SAKIT: { label: "Sakit", tone: "amber", color: "#d89024" },
  IZIN: { label: "Izin", tone: "info", color: "#347fb7" },
  ALPA: { label: "Alpa", tone: "danger", color: "#c34c55" },
  DINAS: { label: "Dinas", tone: "success", color: "#2c966d" },
} as const;

function initials(name: string) { return name.split(" ").map((word) => word[0]).join("").slice(0, 2); }

export default async function MonitoringPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireRoles(["ADMIN", "WAKASEK_KURIKULUM"]);
  const params = await searchParams;
  const rawPeriod = Array.isArray(params.period) ? params.period[0] : params.period;
  const period = normalizeMonitoringPeriod(rawPeriod);
  const filter = parseAttendanceFilter(params);
  const [data, classes] = await Promise.all([getMonitoringData(period, { className: filter.className, status: filter.status, type: filter.type }), db.select({ name: schoolClasses.name }).from(schoolClasses).where(eq(schoolClasses.isActive, true)).orderBy(schoolClasses.grade, schoolClasses.name)]);
  const topClass = data.classSummary[0];
  const priorityCount = data.summary.overdue + data.attendanceSummary.pending;
  const stats = [
    { label: "Jadwal dalam periode", value: data.summary.scheduled, detail: `${period} hari terakhir`, icon: CalendarCheck2, tone: "blue" },
    { label: "Piket selesai", value: data.summary.completed, detail: "dikonfirmasi guru piket", icon: CheckCircle2, tone: "green" },
    { label: "Belum diselesaikan", value: data.summary.overdue, detail: "jadwal yang sudah lewat", icon: AlertTriangle, tone: "red" },
    { label: "Keterlaksanaan", value: `${data.summary.completionRate}%`, detail: `${data.summary.inProgress} sedang berjalan`, icon: Percent, tone: "amber" },
    { label: "Absensi siswa", value: data.attendanceSummary.students, detail: `${data.attendanceSummary.studentStatusCounts.ALPA} alpa · ${data.attendanceSummary.studentStatusCounts.SAKIT} sakit`, icon: GraduationCap, tone: "blue" },
    { label: "Absensi guru", value: data.attendanceSummary.teachers, detail: `${data.attendanceSummary.teacherStatusCounts.ALPA} alpa · ${data.attendanceSummary.teacherStatusCounts.SAKIT} sakit`, icon: UsersRound, tone: "amber" },
    { label: "Menunggu konfirmasi", value: data.attendanceSummary.pending, detail: `${data.attendanceSummary.confirmed} sudah dikonfirmasi`, icon: Clock3, tone: "red" },
  ];
  const statusKeys = Object.keys(statusMeta) as Array<keyof typeof statusMeta>;

  return <>
    <PageHeader title="Analitik kurikulum" description={`Ringkasan keterlaksanaan piket dan absensi ${formatDateId(data.start)} sampai ${formatDateId(data.end)}.`} action={<a className="button button-primary" href={`/api/reports/monitoring?period=${period}&${attendanceFilterParams(filter).toString()}`}><Download /> Ekspor laporan Excel</a>} />
    <form className="monitoring-filter" method="get"><label className="field"><span>Periode</span><select name="period" defaultValue={period}>{[7, 30, 90].map((value) => <option value={value} key={value}>{value} hari</option>)}</select></label><label className="field"><span>Jenis absensi</span><select name="type" defaultValue={filter.type || ""}><option value="">Siswa + Guru</option><option value="SISWA">Siswa</option><option value="GURU">Guru</option></select></label><label className="field"><span>Kelas</span><select name="class" defaultValue={filter.className || ""}><option value="">Semua kelas</option>{classes.map((item) => <option value={item.name} key={item.name}>{item.name}</option>)}</select></label><label className="field"><span>Status</span><select name="status" defaultValue={filter.status || ""}><option value="">Semua status</option><option value="SAKIT">Sakit</option><option value="IZIN">Izin</option><option value="ALPA">Alpa</option><option value="DINAS">Dinas</option></select></label><div><button className="button button-primary" type="submit">Terapkan</button><a className="button button-ghost" href="/monitoring">Reset</a></div></form>
    <section className={`monitoring-insight ${priorityCount ? "needs-attention" : "on-track"}`}><span>{priorityCount ? <AlertTriangle aria-hidden="true" /> : <CheckCircle2 aria-hidden="true" />}</span><div><strong>{priorityCount ? `${priorityCount} item menjadi prioritas tindak lanjut` : "Data kurikulum berada di jalur yang baik"}</strong><p>{priorityCount ? `${data.summary.overdue} jadwal belum selesai dan ${data.attendanceSummary.pending} catatan absensi menunggu konfirmasi.` : `Keterlaksanaan mencapai ${data.summary.completionRate}% dan seluruh catatan sudah dikonfirmasi.`}</p></div><StatusPill tone={priorityCount ? "warning" : "success"}>{priorityCount ? "Perlu perhatian" : "Terkendali"}</StatusPill></section>
    <section className="stat-grid analytics-stat-grid">{stats.map(({ label, value, detail, icon: Icon, tone }) => <article className={`stat-card tone-${tone}`} key={label}><span className={`stat-icon ${tone}`}><Icon /></span><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>)}</section>

    <section className="monitoring-grid">
      <article className="panel chart-panel"><div className="panel-header"><div><h2><CalendarCheck2 /> Keterlaksanaan piket</h2><p>Perbandingan jadwal selesai pada 14 hari terakhir</p></div><span className="chart-legend"><i /> Selesai</span></div><div className="compliance-chart" role="img" aria-label="Grafik persentase keterlaksanaan piket 14 hari terakhir">{data.trend.map((item) => { const rate = item.scheduled ? Math.round(item.completed / item.scheduled * 100) : 0; return <div className="chart-column" key={item.date} title={`${formatDateId(item.date)}: ${item.completed} dari ${item.scheduled} jadwal selesai`}><span>{item.scheduled ? `${rate}%` : "-"}</span><div className="chart-track"><i style={{ height: `${item.scheduled ? Math.max(rate, 5) : 2}%` }} /></div><small>{item.date.slice(8, 10)}/{item.date.slice(5, 7)}</small></div>; })}</div><div className="chart-mobile-summary" aria-label="Rincian keterlaksanaan per hari">{data.trend.map((item) => { const rate = item.scheduled ? Math.round(item.completed / item.scheduled * 100) : 0; return <div key={item.date}><span><strong>{item.date.slice(8, 10)}/{item.date.slice(5, 7)}</strong><small>{item.completed}/{item.scheduled} jadwal selesai</small></span><b>{item.scheduled ? `${rate}%` : "-"}</b></div>; })}</div></article>
      <article className="panel attendance-distribution"><div className="panel-header"><div><h2><GraduationCap /> Status absensi siswa</h2><p>Distribusi khusus siswa pada periode</p></div></div><div className="distribution-body">{statusKeys.map((status) => { const meta = statusMeta[status]; const value = data.attendanceSummary.studentStatusCounts[status]; const percentage = data.attendanceSummary.students ? Math.round(value / data.attendanceSummary.students * 100) : 0; return <div className="distribution-row" key={status}><div><span className="distribution-label"><i style={{ background: meta.color }} />{meta.label}</span><strong>{value}</strong></div><div className="distribution-track"><i style={{ width: `${percentage}%`, background: meta.color }} /></div><small>{percentage}%</small></div>; })}</div><div className="attendance-total"><GraduationCap /><span><strong>{data.attendanceSummary.students} catatan siswa</strong><small>{data.attendanceSummary.confirmed} total terkonfirmasi · {data.attendanceSummary.pending} menunggu</small></span></div></article>
    </section>

    <section className="analytics-grid"><article className="panel attendance-trend-panel"><div className="panel-header"><div><h2><GraduationCap /> Tren absensi siswa</h2><p>Jumlah catatan siswa per hari</p></div></div><div className="attendance-stack-chart" role="img" aria-label="Grafik tren absensi siswa harian">{data.trend.map((item) => { const total = item.studentAttendanceCount || 0; return <div className="stack-column" key={item.date} title={`${formatDateId(item.date)}: ${total} catatan siswa`}><span>{total || "-"}</span><div className="stack-track">{statusKeys.map((status) => <i key={status} style={{ height: `${total ? Math.max(item.studentAttendanceStatuses[status] / total * 100, item.studentAttendanceStatuses[status] ? 4 : 0) : 0}%`, background: statusMeta[status].color }} />)}</div><small>{item.date.slice(8, 10)}</small></div>; })}</div><div className="stack-legend">{statusKeys.map((status) => <span key={status}><i style={{ background: statusMeta[status].color }} />{statusMeta[status].label}</span>)}</div></article><article className="panel attendance-trend-panel"><div className="panel-header"><div><h2><UsersRound /> Tren absensi guru</h2><p>Jumlah catatan guru per hari</p></div></div><div className="attendance-stack-chart" role="img" aria-label="Grafik tren absensi guru harian">{data.trend.map((item) => { const total = item.teacherAttendanceCount || 0; return <div className="stack-column" key={item.date} title={`${formatDateId(item.date)}: ${total} catatan guru`}><span>{total || "-"}</span><div className="stack-track">{statusKeys.map((status) => <i key={status} style={{ height: `${total ? Math.max(item.teacherAttendanceStatuses[status] / total * 100, item.teacherAttendanceStatuses[status] ? 4 : 0) : 0}%`, background: statusMeta[status].color }} />)}</div><small>{item.date.slice(8, 10)}</small></div>; })}</div><div className="stack-legend">{statusKeys.map((status) => <span key={status}><i style={{ background: statusMeta[status].color }} />{statusMeta[status].label}</span>)}</div></article></section>
    <section className="analytics-grid"><article className="panel class-ranking"><div className="panel-header"><div><h2><GraduationCap /> Per kelas</h2><p>Kelas dengan catatan terbanyak</p></div></div><div className="ranking-list">{data.classSummary.slice(0, 8).map((item, index) => <div className="ranking-row" key={item.className}><span className="ranking-index">{index + 1}</span><span className="ranking-name"><strong>{item.className}</strong><small>{item.pending ? `${item.pending} menunggu konfirmasi` : "Semua terkonfirmasi"}</small></span><span className="ranking-value"><strong>{item.total}</strong><small>{item.ALPA} alpa</small></span></div>)}{!data.classSummary.length && <p className="empty-state">Belum ada data absensi siswa.</p>}</div>{topClass && <div className="panel-callout"><Layers3 /> <span><strong>Fokus analisis siswa</strong><small>{topClass.className} memiliki {topClass.total} catatan pada periode ini.</small></span></div>}</article><article className="panel attendance-distribution"><div className="panel-header"><div><h2><UsersRound /> Status absensi guru</h2><p>Distribusi khusus absensi guru</p></div></div><div className="distribution-body">{statusKeys.map((status) => { const meta = statusMeta[status]; const value = data.attendanceSummary.teacherStatusCounts[status]; const percentage = data.attendanceSummary.teachers ? Math.round(value / data.attendanceSummary.teachers * 100) : 0; return <div className="distribution-row" key={status}><div><span className="distribution-label"><i style={{ background: meta.color }} />{meta.label}</span><strong>{value}</strong></div><div className="distribution-track"><i style={{ width: `${percentage}%`, background: meta.color }} /></div><small>{percentage}%</small></div>; })}</div></article></section>

    <section className="analytics-grid analytics-grid-secondary"><article className="panel teacher-performance"><div className="panel-header"><div><h2><UserRoundCheck /> Kinerja guru piket</h2><p>Diurutkan dari tingkat keterlaksanaan terendah</p></div></div><div className="teacher-monitor-list">{data.teacherSummary.map((item) => <div key={item.teacherId}><span className="avatar">{initials(item.teacherName)}</span><span><strong>{item.teacherName}</strong><small>{item.attendanceCount} catatan · {item.overdue} belum</small></span><span className="teacher-rate"><strong>{item.completionRate}%</strong><small>{item.completed}/{item.scheduled} selesai</small></span></div>)}{!data.teacherSummary.length && <p className="empty-state">Belum ada jadwal guru piket.</p>}</div></article><article className="panel shift-summary"><div className="panel-header"><div><h2><Layers3 /> Ringkasan jadwal</h2><p>Satu guru piket untuk setiap hari sekolah.</p></div></div></article></section>

    <article className="panel monitoring-table"><div className="panel-header"><div><h2><ListChecks /> Riwayat keterlaksanaan</h2><p>Status jadwal terbaru dalam periode terpilih</p></div></div><div className="mobile-data-view"><div className="mobile-record-list">{data.occurrences.slice(0, 100).map((item) => <article className="mobile-record" key={`${item.teacherId}-${item.date}`}><div className="mobile-record-heading"><span className="avatar">{initials(item.teacherName)}</span><span><strong>{item.teacherName}</strong><small>{item.weekday} · {formatDateId(item.date)}</small></span><StatusPill tone={item.status === "SELESAI" ? "success" : item.status === "BERJALAN" ? "info" : "danger"}>{item.status === "SELESAI" ? "Selesai" : item.status === "BERJALAN" ? "Berjalan" : "Belum"}</StatusPill></div><dl className="mobile-record-details"><div><dt>Jam</dt><dd>{item.startTime.slice(0, 5)}-{item.endTime.slice(0, 5)}</dd></div><div><dt>Aktivitas</dt><dd>{item.attendanceCount} catatan</dd></div></dl><p className="mobile-record-note">{item.completedAt ? `Diselesaikan ${formatDateTimeId(item.completedAt)}` : "Belum ada waktu penyelesaian"}</p></article>)}{!data.occurrences.length && <p className="empty-state">Belum ada jadwal pada periode ini.</p>}</div></div><div className="table-scroll desktop-data-view"><table><thead><tr><th>Tanggal</th><th>Guru piket</th><th>Jam</th><th>Aktivitas</th><th>Status</th><th>Waktu selesai</th></tr></thead><tbody>{data.occurrences.slice(0, 100).map((item) => <tr key={`${item.teacherId}-${item.date}`}><td><strong>{item.weekday}</strong><small className="table-subtitle">{formatDateId(item.date)}</small></td><td>{item.teacherName}</td><td className="mono">{item.startTime.slice(0, 5)}-{item.endTime.slice(0, 5)}</td><td>{item.attendanceCount} catatan</td><td><StatusPill tone={item.status === "SELESAI" ? "success" : item.status === "BERJALAN" ? "info" : "danger"}>{item.status === "SELESAI" ? "Selesai" : item.status === "BERJALAN" ? "Berjalan" : "Belum"}</StatusPill></td><td>{item.completedAt ? formatDateTimeId(item.completedAt) : "-"}</td></tr>)}{!data.occurrences.length && <tr><td colSpan={6} className="empty-state">Belum ada jadwal pada periode ini.</td></tr>}</tbody></table></div></article>
  </>;
}
