import { loadEnvConfig } from "@next/env";
import { eq } from "drizzle-orm";
import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";
import { schoolClasses, students, studentEnrollments, academicYears } from "../db/schema";

loadEnvConfig(process.cwd());
const connectionString = process.env.DB_CONNECTION;
if (!connectionString) throw new Error("DB_CONNECTION belum diatur.");

const rosterText: Record<string, string> = {
  "7A": `ABDUL AZIS FADILLAH|ADEEVA FAJRI UTOMO|ADZKA MUHAMMAD ARIF|AFIKA ZAHRA ALMAYRA|AHMAD ANABIL ILHAMI|AHMAD OZIL|AHMAD ROVI|AMANDA ZULFA|CHELSEA QUESHA ALEYCA|DESLAN AHZARO|DINI SYAKIRAH AZZAHRAH|EDELWEIS NEISYA SALSABILA HAWWAA|FAIRA NUR AISYAH|FEBRIYANTI|GIANDRA SETYANABELLA|KEMUNING DARA AYU|KEYLA FITRI ANJANI|MARCHYA MERVIE THOMAS|MUHAMAD RADEN FAISAL|MUHAMMAD AZKA ASYAHRI|MUHAMMAD DANU AJI|MUHAMMD YASIN|MUTIARA HARYANTI|NADIA SHANUM GRANADI|NAYRA CAHYA LATIFAH|NURWAHYUNI|RERE ADINDA PUTRI|RIZKI HANAFI|SATRIA KARYA DINNATA|SEIN ALLURA AUBRIANNE SITUMORANG|TAYFUN TEJA PURNAMA|ZAHRA RIYANTO|ZAQCHIERRY EL RAFEEF RAZALI`,
  "7B": `AJI SAKKA|AL DANISH SYA'BANI|ALDO RIO HERMAWAN|ALFIAN JUNIZA PUTRA|ALISHA SAFIA SUNANDAR|ALITA WAHYU SAFRIYANA|BALQIS BATRISIA|CLARA AULIA ZAHRA|DILAH NUR ANGGRAINI|EKA PUTRI GUNAWAN|GILANG SAPUTRA|GILANG ADITYA PRASETYO|KHANSA FATIN NURBIANSYAH|KHANZA AQILA SALSABILA|MARIA ATALEYAH EVELIN|MAULVI FIANA|MOHAMAD REVAN SUGIANTO|MUHAMMAD FAIZAN|MUHAMMAD FAJRI MAULANA HIDAYATULLAH|NAYRA CHEINA SALSABILA|NISYA AYU APRILLIA|RAFFA IQBAL MUZAKHI|RAKA FIRMANSYAH|REYHAN AL FAKHRIE|RUSSEL HARDJOSENTONO|SHAFA ALMIRA PUTRI|SURYA ADITIA SODIK|SYIFA NUR FAUZIAH NASUTION|TITO SETYA LAKSANA|YASKY ARDABILAL YUSUF|ZAHRA ZAIN TITANS ISKANDAR|ZEALITA FEBRIANA`,
  "7C": `ALMAYESA EFLYN WIDYANINGRUM|ALYA KHAIRA ZAHRA|ANDHARA TIAR IZZATUNNISA|ANGGRAENI|ANINDITA KHANSA RAFANI|BATRISYA NUR AFIFAH|CELVIN NAFIS SANJAYA|DAFFA IRFAN YUSRAN|DILLA FATIKA SARI|FEBIOLA AZZAHRA|JANU BISMA YUNANTO|KHOIR ABDULLOH|KRISNA ALFATAH RAMADHAN|MAHER ZANUMANSYAH|MAURA APRILIA|MUFIDA SALSABILA|MUHAMAD AL-IDRUS|MUHAMAD ALIF RAMADHAN|MUHAMMAD NOVAL|MUHAMMAD RAIHAN NAJMUDDIN|MUHAMMAD RASYID|MULQI AL KHADAFI|NURJANAH|RAFA ALZAHRAN|RIFQI RIADI|RISKA MAY SYAROH|SATRIO DWI SAPUTRA|SELVIANI DWI WULANDARI|SHABRINA JULIANA ZAHRA|WIDIA SEPTIANI|YOVI ALBARIN|ZIO ARDAN FIRMANSYAH|ZIVANNA ANGGUN BATARI`,
  "7D": `AIRIN SHOFIE SALSABILA|ALMAYDA BINTANG SANJAYA|ANJANI NATHA SABRINA|AQHILA PUTRI RAMADHANI|AQILLA QUEENNAYA GARNETARIN|ARFA HARUMI|ARKANA AQILA PRATAMA|ARSYA ADHIKA ARKANTARA|AZKA RADYA LAKSANA|BIANKA ZAHRA RAMADHANI|CAHAYA DWI A|CLARA VERNEZIA WIJAYA|DANISH ACHMAD AL FATHAN|DIFTA DWI YUWONO PUTRA|FAHRI RAHMAN KHOIR|GARA BINTANG SETIA PUTRA SINA|HAIKAL DWI ANGARA|ILMIRA PUTRI SAYYIDINA|KEANU DIRGANTARA|KEBZIE PRATAMA|LINTAR PRAKASA|LUTHFI KHAIRULLAH|M FATAHILLAH Z.M|MUHAMAD ARDIANSYAH|MUHAMAD NUR ALFIAN PALMA|MUHAMAD NUR FAISAL|MUHAMMAD RIFQIHANSYAH|RAISA NADA|SALSABILA SUHANA|SILVIA RADISTI|SORAYA NUR KHALIFAH|ZIDAN RAMADHAN`,
  "8A": `ALI HAMZAH|ALWI NUR WAHID|ANISYA FITRI|AZKA AZZALEA|AZZAHRA ILMIYATUN KHASANAH|CAHAYA KIRANA|CARISSA BENAWA|CHANTIKA ZAHRA|DEVINA KRISTIN GULTOM|FARID KEMAL|FIDELIA QUEENSHA FAUZI|FIRDHA DWI ARNIFA PRASETYA|FIRDHAN PRATAMA|JIHAN NISRINA ANASTASYA|KHOIRUL LATIF SABRIANSYAH|LESTARI FITRIANI|MUHAMMAD RIZKI ADI RAMADHANI P S|NAURAH KHAIRIYAH KUSWARA|PUTRI NABILA|RAFI RESTU CIPTA|RAISYA RAMADHANI|RAISYAH DEWI ARSA|REGINA ANASTASYA|RENZO VIRENDRA ATHAYA|REVIANI AULIA POHAN|SELVIA PUTRI AYU|SHAFA SALSABILA ERLINA PUTRI|SILVINA JULIA ARNANDA|SUYUDI`,
  "8B": `ANDRIAN MILANO|ANNISHA APRILYA|ARKHA ALARICE MAHARDIKA|ARWIN JULIANTORO|AYU REVANA NANDINI|CELVIN AFRIZAL SETIAWAN|CHRISTIAN KENZIE|DESSY RAHMAWATI|DIMAS ADITYA|ESTRI ASKIYAH ARRAHIM|FAHMI AZKA ALVIANSYAH|FANNY DWI OCTAVIANI|HAFIZA AULIA RAMADANI|IBRAHIM KOHAR|INDAH RAHAYU PUTRI|JASMINE AURORA RISKY|KAYLA BALQIST AZRA|LUTFI MUSYAFA|MAULIDA HERLINA FEBRIANI|MUHAMAD ANWARUL MASALIK|MUHAMMAD ALIEF|MUHAMMAD REFAN FEBRIANSYAH|MUHAMMAD SYATHIR RAMADHAN|MULYA SITI AZZAHRA MARASABESSY|PAJAR DWI NUGROHO|RADEN NACITA TOTA DIANDRA|RAHMA PUTRI RAMADHANI|RISTA NAINGGOLAN|WILDANUR ROHMAN`,
  "8C": `AHMAD MUKORROBIN|ANDIKA ARSYKIN|AQILA SALSABILA AHMAD|ARFAN MAJDUDDIN|ARYA|DAFFA WIRAWAN|DELISA INDRIANI KOMISA|EVDYRAN MUHAMMAD PUTRA|GALANG RAJA BINTANG|GILANG RAMADHAN|GIO APRILLIO|JEKI REZKIA|KEANDRA RADITYA KURNIAWAN|KENRO LASTIAR PURBA|KHUSNUL CHOTIMAH|MARIO LORENSIUS TINAMBUNAN|MAWAR AUDIYA RIZKI NAKIAH|MUHADI|MUHAMMAD RASYID|MUHAMMAD REZKI ADITIARA|MUJAHIDAH JANNAH|NATASYA HEROKTAVIA|REZA HALID IBRAHIM|WIDYA NUR AFIIFAH|WITDINIAS ADIB MAJENI|ZAHRA ASYILA RAHMAN|ZID ZIDAN AFKARI|ZIDAN MUHAMAD SADEWA`,
  "8D": `AINI APRILLIA UZMA|AJI NURSARJITO|ANINDYA TALITA TSALATSATI|ANITA SYAHWAL|ARYASATYA BUANA AJI SAMUDRA|ASMAH SANTIKA|AVIKA RIZKY ARYANTI|AZAHRA VANYA TAHER|BILQIS MAULUDIA RAHMA|DAFFA FAUZI EDRIANSYAH|DANESHA PUTRI AYUNDRA|DERZI AMOURA|GILANG AFDAN ANGGARA|MARFELLIA ZAHY FAIQAH|MUHAMMAD ASRULY AULIA|MUHAMMAD RAFA RAMADHAN|MUHAMMAD REVALDY SETIAWAN|NAZWA ALVIRA SETIAWAN|NISA MARWAH|NOVAL FAUZAN|RASTI NAINGGOLAN|RIFQI RAMDHAN PUTRA IRAWAN|RIZQI WASI'ATUL CHAULIQ|SABIAN RASYID AUSHAF|SABRINA NURNAILA|SALWA MEITA SHIFANY|SYAKHIRA DWI RAHMANIA|VIRLY DHEA NATASHA|ZAKY AZKA GUSNA`,
  "8E": `AFRIZA TRI RAMADHAN|ARGA MERLINO|ATIKAH ZAHRA|AULIA PUTRI|AZAM FADILAH|CLARISYA NOVA ANDHEA|DEREN ALBERT KRISTIAN|DEWI OKTANANDIRA|DJASMINE SEKAR KINASIH|FLORENCIA ANUGRAH JAPANG|HANIFA HASNA NABILA|INDAH AULIA OKTAVIANI|IRHAM YUSUF HADINATA|JIMMY PUTERA HIDAYAT|KAYLA ANINDYA|KHANSA FILDZAH AZIZAH|MIKHA PRADIKTA|MUHAMMAD ALIF WIBOWO|MUHAMMAD AZKA|MUHAMMAD REFAN|NAIRA SHANNARA MUNARIS|NOVA MAULIDA|NUR SYIFA SALSABILA|PUJIONO|PUTRI TALINDA|RIYANI AL ZAHRA|RIZKI ADRIANSYAH|SAMBOJA ADY PUTRA|SITI NURFADILA`,
  "8F": `ADREA MUHAMMAD RAFIE|AFIQAH KHALIFATU ROHMAH|AL PUTRA ZULWA|AL RAIS MAHARDIKA WILIANSYAH|ALFATIH AJI YUDHANTO|AMIRA ZAHEEN BAKHITA|ARDIYANTI SEPTIANA DEWI|ARYA DHAVASA|AZKA SAPUTRA|DAVINA KINETA SULAEMAN|GABINO VALDEMAR SUNBANU|HARIZ AZ ZUBAIR|IRHAM GHANI FAZA|KHANZANAH ANNISAH PUTRI|LITA YUNIASIH|MUHAMMAD ARIFIN AZIZ|MUHAMMAD FARHAN ZEIN|NABILLA ANGGRAINI PUTRY|NOFRI MOAN MUJHA|RAIHAN RIFALDY ADZHAR|REIFA ANGELLINA|RISKY ADITYA SAPUTRA|SAFANI AZZAHRA|SALWA AZZAHRA|SULTAN AL-SYAKIR PURNOMO|SYAKIRA|TYA ELITA IZZATI|ZAHRA ADZKIYA|ZAIDAN MALIK AHMAD`,
  "8G": `ALIF TOFANNO|ALYSHA KHAIRA WILDA KSATRIAWAN|AVIQA KHAIRUNISA AZAHRA|CARISSA BENAWA|CARISSA RANIA|CARISSA ZAHIRAH KHARIM|DAMAR WICAKSONO|GALANG ARKANA FATH AZIS|KELVIN PRASETYO|MIKHA STEFANI SIMANJUNTAK|MUHAMMAD FAJAR ALFARIDZKY|MUHAMMAD IRSYAD FAIZI|NABILA QAIREEN RAMADHANI|NADINE AZIZAH|NAUFAL DARY ABIYYU|NAYSILA ZAHRA|QUEN SHANIA RAMADHANI|RAFA SAYYID|RAYYA AULIA PUTRI|SANDY HADIANTO|SITI HUMAIROH|STEVEN FEBRIAN VICANTARA|SYABILLA DESVIANTI|YESICA ANGGRAINI BONSERA|ZAHRA TALITA DZAKIRA|ZALFAA NUR MAULINA|ZELDA AYU KINANRASHIDA|ZIAN ZAVARAH HERTALITA`,
  "9A": `ABIYYU HIBRIZI INDRATA|ADRIAN KRISTA PRATAMA|AFIFAH TRY WULANDARI|ANASTASYA|CAHYO LANGGENG|DINDA AURORA RISKI|FAHRUL RAMADHAN|GESYA MANAIRA RAHMADANI|HAICAL SAPUTRA|IMANUEL TOGATOROP|JONATHAN RAFFAEL GURNING|MUH DZIKRI ADRI SYAFII PUTRA SU|MUHAMAD ABDUL ROHMAN|MUTIARA AMALY OKTAVIANI|NADHIFAH SYAHLA MAHARANI|NADJWA APRILIA PUTRI|NATASYA FEBYOLA|PONCO ADYT SETIA|PUTRI NAHAR RAMADHANI|RACHEL JOVITA AZ-ZAHRA|RAYHAN PERMANA PUTRA|RAYVANU PUTRA EFENDI|RAYYA SESHA JUNAIRI|RAZITA SYIFA|REYNA SYIFANA|RIRIN WIDIYA WATI|RIZKY SETIAWAN|SINTAWATI|WILDAN KABIR AQIEL|ZAHRA AULIA RAHMAN`,
  "9B": `ABDURROHMAN AD-DIBA'I|ADRIAN AKBAR SAPUTRA|AJENG KENES NURDANANTI|ARDIANSYAH|AULIA RACHMA|CHRISTOFER KUSUMA|ELVI MERRY NATALIA HUTASOIT|FAIDUR ROFI YASIN|FARADILLAH FHATINIA|IQBAL EL DIMITRI|KAYLA NUR AISA|LUTHFI KHAIRUL MALIK|MARSYA LEONYTHA|MUHAMAD RIFKY HAFIZDI|MUHAMMAD DZILAL FISYAUQI|MUHAMMAD HAFIZ ARSYAD ARROYAN|NATHANAEL HARYADI SIHOMBING|NENGAH AMELIA|PUTRA SUDAN PERKASA|PUTRI HUSNUL KHOTIMAH|QEISYA ADELIA PUTRI|QIARA PUTRI AZWA|RAKHA ANDREALITA|REINA ANATASYA|SANDY|SENANDUNG NACITA|SERGIO DIPATIO MORA SILALAHI|SYABRINA PRATIWI|YULIANI SUYOTO|ZAHRA RAUDHATUL AISYA`,
  "9C": `ADINDA NABILA|ANGELICHA YOLANDA|ANGGUN ZAKIA SOLEHA|ARIF RADITYA|BUNGA SOLEHA PUSPITA SARI|ERLANGGA WIRA BACHTIAR|FADHIL FEBRIANSYAH SETIAWAN|FERLY LEVIANO ALFATHAN|IKHWAN MA'RUF YAFI|JELITA SULISTYA|MELVIN NADIZA PRATAMA|MUHAMAD RIFALDI APRIANSYAH|MUHAMAD RIZKY RAMDAN|MUHAMMAD PASKAH WIJAYA|NABILA TEZIKA ANGGRAENI|NABILAH SAFITRI|NAYLA HAFIZAH|NAZWA ANINDIA PUTRI|RESPATI ADEPUTRI|RINI SAFITRI|ROHIMAN|ROSI PUJI HANDAYANI|SAHLU AL JABAR SETRIMA|SASKIA RODATUL ZAZIRAH|SILVIANA LETISYA|TALITHA RASIKAH|TIARA PUTRI ANGELINE SIMATUPANG|WIRA SATRIA ABIMANYU|YASMIN ADELIA|YOVITA AULIA PUTRI`,
  "9D": `ALFINO MUHAMAD PRAKOSO|ARDIPTA DAMAR PRAMBADA|AZARINE VALENTINA|AZMI AMIRULLAH|BISMA PUTRA RAGIL PALAWA ATBAR|CIKA RAMADAN TRI PUTRI|DHIAFA KHAIRUNISA|DIO FIQHRAM ABIDIN|ERLANGGA ADITYA PUTRA PRATAMA|HADI MAULANA|INTAN AYU LARASATI|KANASYAH ALIKA PUTRI|KAYLA ZAHWA RAMADHANI|LAKA ALBAR ALBADI|MAULIDINA|MUHAMAD FAIZ ALDIANSYAH|MUHAMMAD SAHRONI|NAYAKA ZUHDI MAKARIM|NURAIDAH|NURUL HIKMAH|RAFA FAUZAN KAMIL|REIVA NUR SYEPIA|SABRINA KRISTA BELLA|SANDY SAPUTRA|TIARA INDRIYANTI|UMAR ALI SYAHID|VIBY VIRGIAN EDENMARTIA|YULFIA ANGGRAINI|ZEIN SYAUKAT HANADA`,
  "9E": `ADRIAN SAPTO NUGROHO|ADZKAR AS SYA'BAN|AKBAR BILLAL ALHABSI|CHARISA FELICE SAMANTA|DIAS ALVARO SUPRAPTO|DIMAS ADI ANGGARA PUTRA|DINDA AZZAHRA|FAADIYAH GUNADI|FADHLAN ATHARIZZ|FARHAN RADI|FITRAH AURELLIO|GABRIEL RAFLI SITANGGANG|ILMIANDRA FAIRUZALDI|JUWITA SARVIOLITA HAMBALI|KHANSHA HAILAH|MICHAEL DYLAN ALEXANDER|MUHAMMAD FAKHRI MUBARAK|MUKARAM AZGAR YAQUB KHAN SH|NAIRA CAHYA KAMILA|QUEENTA KINARA MUKTI|RAIHAN ASHYFAQUL GATHFAN|RASYID AL FURQAAN|RATU ALLYSA ADIKIA|SYAVIRA PRATAMI|TASYA APRILIA RAHAWARIN|VALENTINO MESIANO LEOSI|VERLAND CHANIAGO SUSANTO|YOGI FATURRAHMAN|ZAHIRA ADILAH PUTRI|ZIDAN SOFIAN`,
};

function key(value: string) { return value.toLowerCase().replace(/\s+/g, " ").trim(); }

async function main() {
  const client = postgres(connectionString!, { max: 1, prepare: false });
  const db = drizzle(client);
  const classes = await db.select({ id: schoolClasses.id, name: schoolClasses.name }).from(schoolClasses);
  const [activeYear] = await db.select({ id: academicYears.id }).from(academicYears).where(eq(academicYears.isActive, true)).limit(1);
  const result: Array<{ className: string; total: number; added: number; retired: number }> = [];
  await db.transaction(async (tx) => {
    for (const schoolClass of classes) {
      const names = (rosterText[schoolClass.name.toUpperCase()] || "").split("|").map((name) => name.trim()).filter(Boolean);
      if (!names.length) continue;
      const official = new Map(names.map((name) => [key(name), name]));
      const current = await tx.select({ id: students.id, name: students.name, studentNumber: students.studentNumber, isActive: students.isActive }).from(students).where(eq(students.classId, schoolClass.id));
      let added = 0, retired = 0;
      for (const student of current) {
        if (student.isActive && !official.has(key(student.name))) {
          await tx.update(students).set({ status: "PINDAH", isActive: false, updatedAt: new Date() }).where(eq(students.id, student.id));
          retired++;
        }
      }
      for (const name of names) {
        const existing = current.find((student) => key(student.name) === key(name));
        let studentId: number;
        if (existing) {
          studentId = existing.id;
          await tx.update(students).set({ name, classId: schoolClass.id, status: "AKTIF", isActive: true, updatedAt: new Date() }).where(eq(students.id, existing.id));
        } else {
          const [created] = await tx.insert(students).values({ classId: schoolClass.id, name, studentNumber: `GF-${schoolClass.name}-${String(added + 1).padStart(3, "0")}`, status: "AKTIF", isActive: true }).returning({ id: students.id });
          studentId = created.id;
          added++;
        }
        if (activeYear) await tx.insert(studentEnrollments).values({ studentId, classId: schoolClass.id, academicYearId: activeYear.id, outcome: "AKTIF" }).onConflictDoNothing();
      }
      result.push({ className: schoolClass.name, total: names.length, added, retired });
    }
  });
  console.log(JSON.stringify(result, null, 2));
  await client.end();
}
main().catch((error) => { console.error(error); process.exit(1); });
